### ISSUE TITLE
Wanted: setElementArrayByAttribute

### ISSUE THREAD

**Issue by jensbeinke** [gueff/phormix#1]
$aClaimReason = $oPhormix->getElementArrayByAttribute('name', 'claimReason');

        $aClaimReason['filter']['validate']['expect']['value'] = array(11133, 22345);
        $aClaimReason['filter']['validate']['expect']['label'] = array('Warenlieferung', 'Dienstleistung');

        $oPhormix->setElementArrayByAttribute('name', 'claimReason', $aClaimReason);

**Comment by gueff** [comment]
see  `public function setElementArrayByName($sElement = '', array $aValue = array())`:

Here you already can set/overwrite an existing config array of a specific element. 

In your Case it would be:
~~~
$oPhormix->setElementArrayByName('claimReason', $aClaimReason);
~~~
